services:
  portfolio-api:
    build:
      context:: ../../
      dockerfile: Dockerfile
    container_name: portfolio-api-prod
    environment:
      APP_NAME: ${APP_NAME}
      GO_ENV: production
      GO_PORT: ${GO_PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${GO_PORT}:${GO_PORT}"
    healthcheck:
      test:
        ["CMD", "curl", "-X", "OPTIONS", "-f", "http://localhost:${GO_PORT}"]
      interval: 15s
      timeout: 5s
      retries: 5
